{
 "title": "Conjur dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Leader IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conjur_health_status{role=\"master\", globalstatus=\"true\", instance=\"https://10.0.0.43/health\"} + 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "conjur_health_status{role=\"master\", globalstatus=\"true\", instance=\"https://10.0.0.45/health\"} + 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "conjur_health_status{role=\"master\", globalstatus=\"true\", instance=\"https://10.0.0.37/health\"} + 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leader node status in the cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "conjur_health_status{role=\"master\", degraded=\"false\",globalstatus=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failover Cluster Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(conjur_health_status{cluster=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(conjur_health_status{globalstatus=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core node running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "conjur_health_status{role=\"standby\", globalstatus=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "conjur_health_status{role=\"master\", globalstatus=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "${host} Infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "host" },
  {
   "title": "Leader Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "conjur_health_status{role=\"master\", globalstatus=\"true\", instance=~\"https://$host/health\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "conjur_health_status{role=\"standby\", globalstatus=\"true\", instance=~\"https://$host/health\"}+1",
     "legendFormat": "__auto"
    },
    {
     "expr": "conjur_health_status{role=\"follower\", globalstatus=\"true\", instance=~\"https://$host/health\"}+2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${host} Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "conjur_health_status{instance=~\"https://$host/health\", globalstatus=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$host\",name=~\"conjur\",name=~\".+\"})/sum(machine_memory_bytes{instance=~\"$host\"})*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\",name=\"conjur\",name=~\".+\"}[5m]))*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requests /  day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(conjur_http_response_count_total{}[1d])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx requests last day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(conjur_http_response_count_total{status=~\"5..\"}[1d])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Possum Service Master ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "conjur_health_status{instance=~\"https://$host/health\", possum=\"ok\",globalstatus=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conjur_health_free_space_remaining{instance=~\"https://$host/health\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audit Service Master ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "conjur_health_status{instance=~\"https://$host/health\", audit=\"true\", globalstatus=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx requests / day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(conjur_http_response_count_total{status=~\"4..\"}[1d])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time to answer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(conjur_http_response_time_seconds_sum)/sum(conjur_http_response_time_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Service Master ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "conjur_health_status{instance=~\"https://$host/health\", database=\"true\",globalstatus=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-container_start_time_seconds{instance=~\"$host\",name=\"conjur\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UI Service Master ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "conjur_health_status{instance=~\"https://$host/health\", ui=\"ok\",globalstatus=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\",name=~\"conjur\",name=~\".+\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requests / hour",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(conjur_http_response_count_total{instance=~\"$host:4040\"}[1h]))",
     "legendFormat": "{{status}} {{method}}"
    }
   ]
  }
 ]
}